project:
  type: book
  output-dir: _book
  execute-dir: project
book:
  title: "R101: Praktický úvod do R"
  chapters:
    - index.qmd
    - quarto/lekce_01.qmd
    - quarto/lekce_02.qmd
    - quarto/lekce_03.qmd
lang: cs
language:
  code-copy-button-tooltip: "Zkopírovat"
  code-copy-button-title: "Zkopírovat"
  code-copy-button-success: "Zkopírováno"
format:
  html:
    theme: cosmo
    css: quarto/lesson.css
    toc: true
    toc-location: right
    toc-title: "Obsah kapitoly"
    toc-depth: 3
    toc-expand: 1
    number-sections: true
    code-copy: true
    code-fold: false
    code-overflow: scroll
    fig-width: 7
    fig-height: 4.6
    fig-dpi: 120
execute:
  echo: true
  warning: true
  message: false
  error: false
  cache: false
